{% set name = "libnvtiff" %}
{% set version = "0.5.0.67" %}

package:
  name: libnvtiff-split
  version: {{ version }}

{% set arm_variant_type = arm_variant_type | default("sbsa") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}

source:
  - url: "https://developer.download.nvidia.com/compute/nvtiff/redist/libnvtiff/linux-x86_64/libnvtiff-linux-x86_64-0.5.0.67_cuda11-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("11")]
    sha256: "fd637007421edbabce22be69c4a59cd1ca902249256cabc585459255070bfc7c"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("11")]
  - url: "https://developer.download.nvidia.com/compute/nvtiff/redist/libnvtiff/linux-x86_64/libnvtiff-linux-x86_64-0.5.0.67_cuda12-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "7b2f888f89125e4b4541c30b5ceb3ec752c7cd4d5fa9d4f64b702bfb3a7010dc"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://developer.download.nvidia.com/compute/nvtiff/redist/libnvtiff/linux-sbsa/libnvtiff-linux-sbsa-0.5.0.67_cuda11-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("11") and arm_variant_type == "sbsa"]
    sha256: "a7ae5b29204c292992befdfd8d60b91de66fe6900de7f81c35f1b5f88f39963d"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("11") and arm_variant_type == "sbsa"]
  - url: "https://developer.download.nvidia.com/compute/nvtiff/redist/libnvtiff/linux-sbsa/libnvtiff-linux-sbsa-0.5.0.67_cuda12-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
    sha256: "efba42df9cffe46391ca1e1cf800685f0f5b1a3a9a73997e7a8dfe004621e3c3"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
  - url: "https://developer.download.nvidia.com/compute/nvtiff/redist/libnvtiff/windows-x86_64/libnvtiff-windows-x86_64-0.5.0.67_cuda11-archive.zip"  # [win and x86_64 and (cuda_compiler_version or "").startswith("11")]
    sha256: "eac3fdddb5c6d8d6956eec54bfc2a02885ec1c9c878bd85727b23deedd1ba43d"  # [win and x86_64 and (cuda_compiler_version or "").startswith("11")]
  - url: "https://developer.download.nvidia.com/compute/nvtiff/redist/libnvtiff/windows-x86_64/libnvtiff-windows-x86_64-0.5.0.67_cuda12-archive.zip"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "78779b442d2feeb50db7660ff30c2ae71c71b4bffad2950d5f90c12a13503304"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://developer.download.nvidia.com/compute/nvtiff/redist/libnvtiff/linux-aarch64/libnvtiff-linux-aarch64-0.5.0.67_cuda11-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("11") and arm_variant_type == "tegra"]
    sha256: "01737fd52022af68b7472529b045d0aa9acfe30b3c662d5e6cae1b848b9c86fa"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("11") and arm_variant_type == "tegra"]
  - url: "https://developer.download.nvidia.com/compute/nvtiff/redist/libnvtiff/linux-aarch64/libnvtiff-linux-aarch64-0.5.0.67_cuda12-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "tegra"]
    sha256: "1706068310a5beb49bd8b4e506650517457bdc51163f93bf0a50f7fcfdd97c27"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "tegra"]

build:
  number: 1
  skip: true  # [osx or ppc64le or cuda_compiler_version in (None, "None")]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]

outputs:

  - name: libnvtiff{{ version.split(".")[0] }}
    build:
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libnvtiff.so.*            # [linux]
      - Library\bin\nvtiff*.dll       # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cuda") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_compiler_version }}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    test:
      commands:
        - test -L $PREFIX/lib/libnvtiff.so.{{ version.split(".")[0] }}                            # [linux]
        - test -f $PREFIX/lib/libnvtiff.so.{{ version }}                                          # [linux]
        - if not exist %LIBRARY_BIN%\nvtiff_{{ version.split(".")[0] }}.dll exit 1              # [win]
    about:
      summary: The NVIDIA nvTIFF runtime library.
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      description: >-
        This is a runtime package only. Developers should install libnvtiff-dev to build
        with nvTIFF.

  - name: libnvtiff
    requirements:
      run:
        # FIXME: Pin to patch version until 1.0
        - {{ pin_subpackage("libnvtiff" ~ version.split(".")[0], max_pin="x.x.x") }}
    about:
      summary: The NVIDIA nvTIFF runtime library.
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      description: >-
        This is a runtime package only. Developers should install libnvtiff-dev to build
        with nvTIFF.

  - name: libnvtiff-dev
    build:
      run_exports:
        # FIXME: Pin to patch version until 1.0
        - {{ pin_subpackage("libnvtiff" ~ version.split(".")[0], max_pin="x.x.x") }}
        - {{ pin_subpackage("libnvtiff", max_pin="x.x.x") }}
    files:
      - lib/libnvtiff.so                                  # [linux]
      # - lib/pkgconfig/nvtiff*.pc                          # [linux]
      - include/nvtiff*                                   # [linux]
      - Library\include                                   # [win]
      - Library\lib\nvtiff.lib                            # [win]
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_compiler_version }}
        - {{ pin_subpackage("libnvtiff" ~ version.split(".")[0], exact=True) }}
        - {{ pin_subpackage("libnvtiff", max_pin="x.x.x") }}
      run:
        - {{ pin_subpackage("libnvtiff" ~ version.split(".")[0], exact=True) }}
        - {{ pin_subpackage("libnvtiff", max_pin="x.x.x") }}
    test:
      commands:
        - test -L $PREFIX/lib/libnvtiff.so                                    # [linux]
        # - test -f $PREFIX/lib/pkgconfig/nvtiff*.pc                            # [linux]
        - test -f $PREFIX/include/nvtiff_version.h                            # [linux]
        - test -f $PREFIX/include/nvtiff.h                                    # [linux]
        - if not exist %LIBRARY_INC%\nvtiff_version.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\nvtiff.h exit 1                          # [win]
        - if not exist %LIBRARY_LIB%\nvtiff.lib exit 1                        # [win]

  - name: libnvtiff-static
    build:
      skip: True  # [not linux]
    files:
      - lib/libnvtiff_static.a  # [linux]
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - cuda-version {{ cuda_compiler_version }}
      run:
        - {{ pin_subpackage("libnvtiff-dev", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/libnvtiff_static.a  # [linux]
    about:
      summary: The NVIDIA nvTIFF static library.
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      description: >-
        This is a developer package only. Developers should install this package to link
        statically to nvTIFF.

about:
  home: https://docs.nvidia.com/cuda/nvtiff/
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: The NVIDIA nvTIFF development package.
  description: >-
    nvTIFF is a GPU accelerated TIFF(Tagged Image File Format) encode/decode library built
    on the CUDA platform. The library is supported on Volta+ GPU architectures.
  doc_url: https://docs.nvidia.com/cuda/nvtiff/

extra:
  feedstock-name: libnvtiff
  recipe-maintainers:
    - conda-forge/cuda
