build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
provider:
  linux_aarch64: default
  linux_ppc64le: default
os_version:
  linux_64: alma8
  linux_aarch64: alma8
  linux_ppc64le: alma8
